name: Build Module

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '**.md'
      - '.github/**'
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - '**.md'
      - '.github/**'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Dynamic Properties Injection
        id: version_info
        run: |
          export TZ="Asia/Shanghai"
          TIME_SUFFIX=$(date +'%Y%m%d%H%M%S')
          NEW_VERSION_CODE=$(date +'%Y%m%d%H%M%S')

          MOD_ID=$(grep -G '^id=' module/module.prop | cut -d= -f2 | tr -d '\r')
          ORIGINAL_VERSION=$(grep -G '^version=' module/module.prop | cut -d= -f2 | tr -d '\r')
          
          NEW_VERSION="${ORIGINAL_VERSION}-${TIME_SUFFIX}-ci"

          echo "=========================================="
          echo "原始版本名: $ORIGINAL_VERSION"
          echo "注入版本名: $NEW_VERSION"
          echo "注入版本号: $NEW_VERSION_CODE"
          echo "=========================================="

          sed -i "s/^version=.*/version=${NEW_VERSION}/" module/module.prop
          sed -i "s/^versionCode=.*/versionCode=${NEW_VERSION_CODE}/" module/module.prop

          echo "version=${NEW_VERSION}" >> $GITHUB_OUTPUT
          echo "mod_id=${MOD_ID}" >> $GITHUB_OUTPUT

      - name: Pack Module to Zip
        run: |
          cd module
          # 使用 . 打包当前目录所有文件，并排除内部可能存在的 .zip 文件
          zip -r ../${{ steps.version_info.outputs.mod_id }}-${{ steps.version_info.outputs.version }}.zip . -x "*.zip"
          cd ..

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.version_info.outputs.mod_id }}-${{ steps.version_info.outputs.version }}
          path: "*.zip"
          retention-days: 30
          compression-level: 0